name: andasy-action
author: Andasy Labs
description: The andasy Github action for deploying application to andasy platform.
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  build_mode:
    description: "Build mode to use between remote, or local (Docker runtime in Github Actions)"
    default: "local"
  project_path:
    description: "Specify a directory to deploy relative to the root of your respository. root directory used by default."
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
